api/urls.py
from django.urls import path
from rest_framework import routers

from api.views.views_bot import UserTgView, MessageView


router = routers.SimpleRouter()
router.register(r'user_tg', UserTgView)

app_name = 'api'

urlpatterns = [
    path('message/<int:pk>/', MessageView.as_view()),
    path('message/', MessageView.as_view()),
]

urlpatterns += router.urls

config/urls.py
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


# Pillow (картинки)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('djoser/', include('djoser.urls.authtoken')),
    path('users/', include('src.users.urls')),
    path('api/', include('api.urls')),
    path('', include('src.common.urls')),

    # path('accounts/', include('allauth.urls')),

    # YOUR PATTERNS
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]

# Для статики:
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/common/urls.py
from django.urls import path

from src.common.views.views import UserLoginView, UserRegistrationView, UserUpdateView, EmailVerificationView


app_name = 'common'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('verify/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='verify'),
]

src/users/urls.py
from django.urls import path

from src.users.views.users import RegistrationView, ChangePasswordView, MeView


app_name = 'users'

urlpatterns = [
    path('users/reg/', RegistrationView.as_view(), name='reg'),
    path('users/changepass/', ChangePasswordView.as_view(), name='changepass'),
    path('users/me/', MeView.as_view(), name='me'),

]

src/users/models.py
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models

from .managers import CustomUserManager


class User(AbstractUser):
    # username = None # уберет вообще это поле, только тогда надо будет удалить его в CustomManagere везде
    username = models.CharField(
        max_length=64, unique=True, null=True, blank=True, verbose_name='Никнейм'
    ) # делаем поле уникальным для выбора поля для логина
    email = models.EmailField(unique=True, null=True, blank=True, verbose_name='Почта') # делаем поле уникальным для выбора поля для логина
    phone_number = PhoneNumberField(null=True, blank=True, unique=True, verbose_name='Телефон') # делаем поле уникальным для выбора поля для логина
    tg_user_id = models.IntegerField(null=True, blank=True, verbose_name='Телеграм ID')
    avatar = models.ImageField(upload_to='image/avatar_user/', null=True, blank=True, verbose_name='Фотография')

    is_verified = models.BooleanField(default=False, verbose_name='Верификация')

    USERNAME_FIELD = 'username' # поле должно быть уникальным какое поле используется логин по умолчанию username
                                # но так прописали backends то username проверяется по  username, mail, phone_number
    # REQUIRED_FIELDS = [] # обязательные поля

    objects = CustomUserManager() # переопределяем менеджер на свой

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        unique_together = ('username', 'email',) # делаем уникальный составной ключ

    @property # можем обратиться к full_name но в модели его не будет
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return f'{self.full_name} ({self.pk})'


class Profile(models.Model):
    GENDER = [
        ('Man', 'Man'),
        ('Woman', 'Woman'),
    ]
    user = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name='profile',
        verbose_name='Пользователь')
    gender = models.CharField(max_length=6, choices=GENDER, default='Man', verbose_name='Пол')
    info = models.CharField(max_length=512, verbose_name='Информация')

    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

    def __str__(self):
        return f'{self.user} ({self.pk})'

src/common/forms/users_forms.py
import uuid
from datetime import timedelta
from django.utils.timezone import now
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from django.contrib.auth import get_user_model

from src.common.models import EmailVerification

User = get_user_model()


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'
    }))
    class Meta:
        model = User
        fields = ('username', 'password',)


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    def save(self, commit=True):
        '''Создается объект EmailVerification при создании нового пользователя
            и отправляем на него ссылку подтверждения'''
        # получаем объект пользователя из заполненной формы и сохраняем его
        user = super(UserRegistrationForm, self).save(commit=True)
        # время жизни ссылки
        expiration = now() + timedelta(hours=48)
        # формируем и записываем объект EmailVerification
        record = EmailVerification.objects.create(
            code=uuid.uuid4(),
            user=user,
            expiration=expiration
        )
        # Вызываем метод прописанный в модели для отправки email
        record.send_verification_mail()
        return user # возвращаем пользователя

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserUpdateForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}), required=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}), required=False)
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'custom-file-input'}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4', 'readonly': True}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'image', 'username', 'email']

src/users/views/users.py
import pdb
from pprint import pprint
from loguru import logger

from django.contrib.auth import get_user_model
from drf_spectacular.utils import extend_schema_view, extend_schema
from rest_framework import generics
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.status import HTTP_204_NO_CONTENT
from rest_framework.views import APIView

from src.users.serializers.api.users import (
    RegistrationSerializer, ChangePasswordSerializer, MeSerializer, MeUpdateSerializer)

User = get_user_model()


@extend_schema_view(
    post=extend_schema(summary='Регистрация', tags=['Аутентификация и регистрация']),
)
class RegistrationView(generics.CreateAPIView):
    '''регистрация пользователя'''

    queryset = User.objects.all()
    permission_classes = [AllowAny]
    serializer_class = RegistrationSerializer


@extend_schema_view(
    post=extend_schema(
        request=ChangePasswordSerializer,  # что бы в документации было видно какие данные мы ожидаем
        summary='Смена пароля', tags=['Аутентификация и регистрация']),
)
class ChangePasswordView(APIView):
    '''Изменение пароля пользователя'''

    def post(self, request):
        logger.info(request.__dict__)
        user = request.user
        serializer = ChangePasswordSerializer(
            instance=user, data=request.data
        )
        # pdb.set_trace()
        logger.info(self.request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(status=HTTP_204_NO_CONTENT)


@extend_schema_view(
    get=extend_schema(summary='профиль пользователя', tags=['Пользователи']),
    put=extend_schema(summary='изменить профиль пользователя', tags=['Пользователи']),
    patch=extend_schema(summary='изменить частично профиль пользователя', tags=['Пользователи']),
)
class MeView(generics.RetrieveUpdateAPIView):
    '''что бы в запросе не отправлять pk переопределяем метод get_object
    и ставим pk=self.request.user, переопределяем get_serializer_class для использования
    разных сериализаторов под разные методы запросов GET, PUT, PATCH'''

    queryset = User.objects.all()
    serializer_class = MeSerializer
    http_method_names = ('get', 'patch', ) # метод пут скрыл из-за ненадобности

    def get_serializer_class(self):
        '''переопределяем get_serializer_class для использования
        разных сериализаторов под разные методы запросов GET, PUT, PATCH'''
        logger.info(self.request.__dict__)
        if self.request.method in ['PUT', 'PATCH']:
            return MeUpdateSerializer
        return MeSerializer

    def get_object(self):
        '''что бы в запросе не отправлять pk переопределяем метод get_object
        и ставим pk=self.request.user'''
        return self.request.user

templates/users/email_verification.html
{% extends 'baseme.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Поздравляем</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Ваша учетная запись успешно подтверждена!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'common:login' %}">Продолжить</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/users/login.html
{% extends 'baseme.html' %}

{#{% load socialaccount %}#}


{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if messages or form.non_field_errors %}
                        <div class="alert
                        {% if messages %} alert-success {% else %} alert-warning {% endif %}
                         alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'common:login' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                        Имя пользователя
                                    </label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a href="#">
                                        <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'common:registration' %}">Нужен аккаунт?
                                Зарегистрируйся!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/users/profile.html
{% extends 'baseme.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'default_avatar.jpg' %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url 'common:profile' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">
                                    Выберите изображение
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                Адрес электронной почты
                            </label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">

            </div>
        </div>
    </div>
{% endblock %}

templates/users/registration.html
{% extends 'baseme.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                             style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'common:registration' %}" method="post">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'common:login' %}" >
                                    Уже есть аккаунт? Авторизоваться
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content%}